### ISSUE TITLE
missing assets in latest docker image

### ISSUE THREAD

**Issue by nochte** [abuisine/docker-resque-web#1]
F, [2017-02-11T13:49:51.643118 #1] FATAL -- : [e64b182d-7615-47ed-835a-eb807e792d05] ActionView::Template::Error (couldn't find file 'twitter-bootstrap-static/fontawesome' with type 'text/css'
Checked in these paths:
  /resque-scheduler-web/app/assets/config
  /resque-scheduler-web/app/assets/images
  /resque-scheduler-web/app/assets/javascripts
  /resque-scheduler-web/app/assets/stylesheets
  /resque-scheduler-web/vendor/assets/javascripts
  /resque-scheduler-web/vendor/assets/stylesheets
  /usr/local/bundle/gems/resque-scheduler-web-1.1.0/app/assets/javascripts
  /usr/local/bundle/gems/resque-scheduler-web-1.1.0/app/assets/stylesheets
  /usr/local/bundle/gems/resque-web-0.0.9/app/assets/images
  /usr/local/bundle/gems/resque-web-0.0.9/app/assets/javascripts
  /usr/local/bundle/gems/resque-web-0.0.9/app/assets/stylesheets
  /usr/local/bundle/gems/twitter-bootstrap-rails-4.0.0/app/assets/fonts
  /usr/local/bundle/gems/twitter-bootstrap-rails-4.0.0/app/assets/javascripts
  /usr/local/bundle/gems/twitter-bootstrap-rails-4.0.0/app/assets/stylesheets
  /usr/local/bundle/gems/twitter-bootstrap-rails-4.0.0/vendor/assets/stylesheets
  /usr/local/bundle/gems/jquery-rails-4.2.2/vendor/assets/javascripts

...snip

**Comment by abuisine** [comment]
Hi nate,
can you share the Dockerfile / docker compose and versions you are using please ? so that I can reproduce

**Comment by nochte** [comment]
Seems to be resolved now

**Comment by nochte** [comment]
I am running it in this way:

`docker service create --stop-grace-period 30s --label com.df.notify=true --label com.df.distribute=true --label com.df.serviceDomain='<snip>' --label com.df.servicePath=/ --label com.df.port=3000    -e RAILS_RESQUE_REDIS=<snip>:6379:0 -e RESQUE_WEB_HTTP_BASIC_AUTH_USER=<snip> -e RESQUE_WEB_HTTP_BASIC_AUTH_PASSWORD=<snip> --network proxy --network <snip> --name <snip: service name> abuisine/resque-web:2.2.0`

**Comment by nochte** [comment]
The image and has i'm using: `abuisine/resque-web@sha256:a0783be972552d2ce67636a4960703b9b7b41c6fa2762dc8e542c684a659b428`

**Comment by abuisine** [comment]
I will probably leave the automated stuff on a latest tag in order to avoid
such problem and tag manually a version that I test on my side

**Comment by abuisine** [comment]
Just tested the actual 2.2.0 and it seems to work correctly.
Will change the version scheme ... at some point :)

**Comment by nochte** [comment]
Sill seeing the same, after pulling 2.2.0 and relaunching via the same method.

**Comment by nochte** [comment]
Fell back to 2.1.0, works fine.

**Comment by abuisine** [comment]
Does it prevents you from using the solution, do you see a visual impact ?

**Comment by stefanahman** [comment]
Yes, I'm getting a fatal error and the classical "Something went wrong".

**Comment by abuisine** [comment]
Regarding the something went wrong, my mistake the documentation stated `/resque-web` as the url path whereas it is `/resque_web`

**Comment by abuisine** [comment]
@nochte would you be able to test the 2.4.0 ?
